---
abstract: 'access KSplice Uptrack web API'
author:
  - 'Steve Huff <shuff@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Uptrack
provides:
  WebService::Uptrack:
    file: lib/WebService/Uptrack.pm
    version: v0.0.1
requires:
  Carp: 0
  Data::Dumper: 0
  HTTP::Request: 0
  HTTP::Response: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::StrictConstructor: 0
  Readonly: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.1
